name: Do the test
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        users: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        run: ./gradlew build